build:
  version: 5.1

accounts:
  message: "Welcome To Bank account related to local API DEV / Cards Test"
  contactDetails:
    name: "Dev Application Configuration for Cards Microservices"
    email: "card@microservice.com"
  onCallSupport:
    112-2321-976
    112-2321-977