build:
  version: 0.1

accounts:
  message: "Welcome To Bank account related to local API /  Default Cards"
  contactDetails:
    name: "Default Application Configuration for Cards Microservices"
    email: "card@microservice.com"
  onCallSupport:
    112-2321-976
    112-2321-977