build:
  version: 0.1

accounts:
  message: "Default Welcome To Bank account related to local API / Loans Default"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@doe.com"
  onCallSupport:
    1010101010
    11100101010